export const pieces = [
  {
    slug: "paeonia-officinalis-042",
    numero: "042",
    latin: "Paeonia officinalis",
    type: "Bouquet",
    provenance: "en Provence",
    recolte: "12 mai 2026",
    prix: 145,
    statut: "disponible",
    icon: "peony",
    note: "Composée avec des pivoines de fin de saison, cueillies à la main.",
    certificat: { region: "en Provence", sechage: "18 jours" },
  },
  {
    slug: "ranunculus-asiaticus-038",
    numero: "038",
    latin: "Ranunculus asiaticus",
    type: "Bouquet",
    provenance: "dans la Drôme",
    recolte: "3 avril 2026",
    prix: 89,
    statut: "disponible",
    icon: "ranunculus",
    certificat: {
      region: "dans la Drôme",
      sechage: "21 jours",
    },
  },
  {
    slug: "eucalyptus-cinerea-039",
    numero: "039",
    latin: "Eucalyptus cinerea",
    type: "Couronne",
    provenance: "dans le Luberon",
    recolte: "15 février 2026",
    prix: 120,
    statut: "disponible",
    icon: "eucalyptus",
    certificat: { region: "dans le Luberon", sechage: "14 jours" },
  },
  {
    slug: "craspedia-globosa-031",
    numero: "031",
    latin: "Craspedia globosa",
    type: "Bouquet",
    provenance: "en Normandie",
    recolte: "8 janvier 2026",
    prix: 78,
    statut: "vendue",
    icon: "craspedia",
    certificat: { region: "en Normandie", sechage: "25 jours" },
  },
  {
    slug: "delphinium-consolida-040",
    numero: "040",
    latin: "Delphinium consolida",
    type: "Bouquet",
    provenance: "en Provence",
    recolte: "20 avril 2026",
    prix: 95,
    statut: "disponible",
    icon: "delphinium",
    certificat: { region: "en Provence", sechage: "20 jours" },
  },
  {
    slug: "rosa-damascena-043",
    numero: "043",
    latin: "Rosa damascena",
    type: "Bouquet",
    provenance: "au Kenya",
    recolte: "2 mai 2026",
    prix: 155,
    statut: "disponible",
    icon: "rose",
    certificat: { region: "au Kenya", sechage: "22 jours" },
  },
  {
    slug: "hydrangea-macrophylla-044",
    numero: "044",
    latin: "Hydrangea macrophylla",
    type: "Bouquet",
    provenance: "en Bretagne",
    recolte: "18 juin 2026",
    prix: 110,
    statut: "disponible",
    icon: "hydrangea",
    certificat: { region: "en Bretagne", sechage: "16 jours" },
  },
  {
    slug: "lavandula-angustifolia-045",
    numero: "045",
    latin: "Lavandula angustifolia",
    type: "Bouquet",
    provenance: "en Provence",
    recolte: "10 juillet 2026",
    prix: 68,
    statut: "disponible",
    icon: "lavande",
    certificat: { region: "en Provence", sechage: "15 jours" },
  },
  {
    slug: "gypsophila-paniculata-046",
    numero: "046",
    latin: "Gypsophila paniculata",
    type: "Bouquet",
    provenance: "aux Pays-Bas",
    recolte: "5 mars 2026",
    prix: 72,
    statut: "disponible",
    icon: "gypsophile",
    certificat: { region: "aux Pays-Bas", sechage: "12 jours" },
  },
  {
    slug: "helichrysum-italicum-047",
    numero: "047",
    latin: "Helichrysum italicum",
    type: "Bouquet",
    provenance: "en Provence",
    recolte: "22 juin 2026",
    prix: 82,
    statut: "vendue",
    icon: "immortelle",
    certificat: { region: "en Provence", sechage: "19 jours" },
  },
  {
    slug: "limonium-sinuatum-048",
    numero: "048",
    latin: "Limonium sinuatum",
    type: "Bouquet",
    provenance: "en Espagne",
    recolte: "14 mai 2026",
    prix: 75,
    statut: "disponible",
    icon: "statice",
    certificat: { region: "en Espagne", sechage: "14 jours" },
  },
  {
    slug: "cortaderia-selloana-049",
    numero: "049",
    latin: "Cortaderia selloana",
    type: "Bouquet",
    provenance: "en Argentine",
    recolte: "30 septembre 2025",
    prix: 130,
    statut: "disponible",
    icon: "pampa",
    certificat: { region: "en Argentine", sechage: "28 jours" },
  },
  {
    slug: "lagurus-ovatus-050",
    numero: "050",
    latin: "Lagurus ovatus",
    type: "Bouquet",
    provenance: "en Italie",
    recolte: "8 août 2025",
    prix: 65,
    statut: "disponible",
    icon: "lagurus",
    certificat: { region: "en Italie", sechage: "13 jours" },
  },
  {
    slug: "protea-cynaroides-051",
    numero: "051",
    latin: "Protea cynaroides",
    type: "Bouquet",
    provenance: "en Afrique du Sud",
    recolte: "11 avril 2026",
    prix: 175,
    statut: "disponible",
    icon: "protea",
    flag: "Pièce rare",
    note: "Une des espèces les plus difficiles à trouver de la collection.",
    certificat: { region: "en Afrique du Sud", sechage: "30 jours" },
  },
  {
    slug: "anemone-coronaria-052",
    numero: "052",
    latin: "Anemone coronaria",
    type: "Bouquet",
    provenance: "en Provence",
    recolte: "6 mars 2026",
    prix: 92,
    statut: "vendue",
    icon: "anemone",
    certificat: { region: "en Provence", sechage: "17 jours" },
  },
  {
    slug: "papaver-rhoeas-053",
    numero: "053",
    latin: "Papaver rhoeas",
    type: "Bouquet",
    provenance: "dans le Gers",
    recolte: "19 juin 2026",
    prix: 88,
    statut: "disponible",
    icon: "coquelicot",
    illustration: "/flowers/coquelicot-v4.png",
    featured: true,
    flag: "Coup de cœur du moment",
    note: "Le premier essai de notre nouvelle identité visuelle, testé grandeur nature.",
    certificat: { region: "dans le Gers", sechage: "16 jours" },
  },
  {
    slug: "centaurea-cyanus-054",
    numero: "054",
    latin: "Centaurea cyanus",
    type: "Bouquet",
    provenance: "en Normandie",
    recolte: "25 juin 2026",
    prix: 70,
    statut: "disponible",
    icon: "bleuet",
    certificat: { region: "en Normandie", sechage: "15 jours" },
  },
  {
    slug: "amaranthus-caudatus-055",
    numero: "055",
    latin: "Amaranthus caudatus",
    type: "Bouquet",
    provenance: "au Pérou",
    recolte: "2 octobre 2025",
    prix: 98,
    statut: "disponible",
    icon: "amarante",
    certificat: { region: "au Pérou", sechage: "23 jours" },
  },
  {
    slug: "celosia-cristata-056",
    numero: "056",
    latin: "Celosia cristata",
    type: "Bouquet",
    provenance: "en Thaïlande",
    recolte: "14 août 2025",
    prix: 105,
    statut: "disponible",
    icon: "celosie",
    certificat: { region: "en Thaïlande", sechage: "20 jours" },
  },
  {
    slug: "achillea-millefolium-057",
    numero: "057",
    latin: "Achillea millefolium",
    type: "Bouquet",
    provenance: "dans les Alpes",
    recolte: "20 juillet 2026",
    prix: 66,
    statut: "disponible",
    icon: "achillee",
    certificat: { region: "dans les Alpes", sechage: "14 jours" },
  },
  {
    slug: "helianthus-annuus-058",
    numero: "058",
    latin: "Helianthus annuus",
    type: "Bouquet",
    provenance: "dans le Gers",
    recolte: "28 août 2025",
    prix: 80,
    statut: "disponible",
    icon: "tournesol",
    certificat: { region: "dans le Gers", sechage: "18 jours" },
  },
  {
    slug: "matricaria-chamomilla-059",
    numero: "059",
    latin: "Matricaria chamomilla",
    type: "Bouquet",
    provenance: "en Anjou",
    recolte: "9 juin 2026",
    prix: 62,
    statut: "disponible",
    icon: "camomille",
    certificat: { region: "en Anjou", sechage: "12 jours" },
  },
  {
    slug: "gossypium-herbaceum-060",
    numero: "060",
    latin: "Gossypium herbaceum",
    type: "Bouquet",
    provenance: "en Grèce",
    recolte: "5 novembre 2025",
    prix: 115,
    statut: "disponible",
    icon: "coton",
    certificat: { region: "en Grèce", sechage: "26 jours" },
  },
  {
    slug: "eryngium-planum-061",
    numero: "061",
    latin: "Eryngium planum",
    type: "Bouquet",
    provenance: "en Écosse",
    recolte: "15 juillet 2026",
    prix: 85,
    statut: "disponible",
    icon: "chardon",
    certificat: { region: "en Écosse", sechage: "17 jours" },
  },
  {
    slug: "banksia-menziesii-062",
    numero: "062",
    latin: "Banksia menziesii",
    type: "Bouquet",
    provenance: "en Australie",
    recolte: "3 mai 2026",
    prix: 160,
    statut: "disponible",
    icon: "banksia",
    flag: "Pièce rare",
    note: "Ramenée d'un des fournisseurs les plus lointains de la collection.",
    certificat: { region: "en Australie", sechage: "29 jours" },
  },
];

export const archiveCount = 47;

export const recentlySold = [
  "Craspedia globosa",
  "Anemone coronaria",
  "Protea cynaroides",
  "Nigella damascena",
];

export const journalArticles = [
  {
    slug: "fleur-sechee-ne-meurt-jamais",
    icon: "sprout",
    titre: "Pourquoi une fleur séchée ne meurt vraiment jamais",
    extrait:
      "Le procédé qui retire l'eau sans retirer la couleur — et pourquoi une pièce peut traverser dix ans sans faner.",
    contenu:
      "Une fleur fraîche fane parce que ses cellules perdent leur eau de façon désordonnée : les parois cellulaires s'effondrent, les pigments se dégradent. Le séchage à l'envers, lent et à l'abri de la lumière, retire l'eau progressivement tout en laissant la structure et une grande partie du pigment intacts. C'est cette lenteur qui fait toute la différence entre une fleur qui s'effondre et une pièce qui traverse les années.",
  },
  {
    slug: "entretenir-piece-sechee",
    icon: "heart",
    titre: "Entretenir une pièce séchée : les gestes qui la font durer",
    extrait:
      "Lumière, poussière, humidité — les trois règles simples pour garder votre spécimen intact des années.",
    contenu:
      "Trois ennemis seulement : le soleil direct (qui décolore), l'humidité (qui ramollit et fait moisir), et la poussière (qui s'accumule dans les pétales). Placez votre pièce loin d'une fenêtre plein sud, dans une pièce sèche, et dépoussiérez-la une fois par mois avec un sèche-cheveux à air froid, jamais avec un plumeau qui casserait les pétales.",
  },
  {
    slug: "offrir-un-souvenir",
    icon: "gift",
    titre: "Offrir un souvenir plutôt qu'un instant",
    extrait: "Pourquoi une fleur qui reste change ce que veut dire \"offrir des fleurs\".",
    contenu:
      "Offrir des fleurs fraîches, c'est offrir une semaine. Offrir une pièce séchée, c'est offrir un objet qui reste dans la maison de quelqu'un pendant des années, qui lui rappelle qui la lui a offerte à chaque fois qu'elle la regarde. C'est un changement de nature du cadeau, pas seulement de durée.",
  },
];

export function getPieceBySlug(slug) {
  return pieces.find((p) => p.slug === slug);
}

export function getArticleBySlug(slug) {
  return journalArticles.find((a) => a.slug === slug);
}

// Pièces déjà collectionnées par le client connecté — données factices en
// attendant qu'un vrai compte Supabase soit branché (voir lib/supabase.js).
export const mockCarnet = {
  possedees: [
    { numero: "042", latin: "Paeonia officinalis", icon: "peony", acquiseLe: "12 mai 2026" },
    { numero: "038", latin: "Ranunculus asiaticus", icon: "ranunculus", acquiseLe: "3 avril 2026" },
    { numero: "039", latin: "Eucalyptus cinerea", icon: "eucalyptus", acquiseLe: "15 février 2026" },
  ],
  manquantes: [
    { latin: "Craspedia globosa", statut: "Déjà vendue à quelqu'un d'autre" },
    { latin: "Delphinium consolida", statut: "Disponible dans la galerie", slug: "delphinium-consolida-040" },
    { latin: "Espèce inconnue", statut: "À découvrir dans une prochaine collection" },
    { latin: "Espèce inconnue", statut: "À découvrir dans une prochaine collection" },
  ],
};
